### ISSUE TITLE
楼主，我给一些学术上的建议

### ISSUE THREAD

**Issue by zhengwh** [open-power-workgroup/Hospital#112]
你使用rst的ReadMe，或者你看一下github的md的ReadMe是否支持 页面内引用 ，类似于做参考 文献的方式。

有一个readme.rst可以参考一下。https://github.com/GeeTeam/gt-java-sdk

https://github.com/GeeTeam/gt-java-sdk#geetest-user-guid

另外，为作者这种利国利民的举动点赞。

**Comment by zhengwh** [comment]
这样做的好处是：

- 使用学术论文的风范，严谨可信
- 避免别人说你造谣，因为这些都有依据
- 你的论点是可证伪的科学，只要别人能把你的参考文献推导，你就可以更正信息
- 你可以规避掉很多法律风险

如果关于rst语法不明白的地方，可以查看官方文档。但是基本我觉得参考 我发的那个链接里面的内容的格式，搬套上去就OK了。

**Comment by xokctah** [comment]
建议已收到。我们整理完数据结构后就纳入考虑。多谢 @zhengwh
