### ISSUE TITLE
Please add an English READ_ME, 不然老外看到会很困扰的

### ISSUE THREAD

**Issue by smarxpan** [open-power-workgroup/Hospital#118]
毕竟这里是github, 老外点进来都不知道啥东西

**Comment by peerless2012** [comment]
After all here is Github,the foreigner don't know what the fuck is this when he click in.

**Comment by binarywang** [comment]
why do me care？

**Comment by Rodeoclash** [comment]
This repo has shown up twice in trending repo emails that go out daily. I'm curious about what this project is doing.

**Comment by Neroldy** [comment]
@Rodeoclash Well man, this is a Chinese hospitals list.

**Comment by Rodeoclash** [comment]
A comment in this thread (seems to have been deleted now) was that this was a list of Chinese hospitals.

**Comment by Krabapple** [comment]
@Rodeoclash 
Actually this is a list of Putian hospitals in China.
Putian hospitals are all privately owned. The doctors there are of poor quality. They took a lot of money from the patients and treated them badly.
Here's a report: http://www.scmp.com/news/china/policies-politics/article/1940668/baidu-scandal-spotlight-china-military-hospitals

**Comment by dochang** [comment]
@binarywang There're many foreigners who live in China or plan to come here.  We MUST NOT kill them.  I hope these PUTIAN-related projects could be great living guides for anyone.

**Comment by chantisnake** [comment]
I will try to add an English readme, but this can wait.
