### ISSUE TITLE
怎么知道医院是不是莆田系的？

### ISSUE THREAD

**Issue by uncode** [open-power-workgroup/Hospital#119]

**Comment by FDKPIBC** [comment]
https://github.com/langhua9527/BlackheartedHospital/blob/master/guidance.md

**Comment by zhoubhin** [comment]
进官网看看（有官网的话），如果你看到导航栏上有一堆类似党风建设、团队建设、党员风采等你看都不想看的按钮时，应该就是正规医院；而你进了网站之后，各种在屏幕上飞来闪去的问你要不要咨询的弹窗，那就是莆田系医院了

**Comment by LeonJavaAndroid** [comment]
http://m.uczzd.cn/webapp/webview/article/news.html?app=uc-iflow&aid=13375223841082283435&cid=1525483516&zzd_from=uc-iflow&uc_param_str=dndseiwifrvesvntgipf&recoid=11979565362996552782&rd_type=reco&pagetype=share

查看全文

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate
