### ISSUE TITLE
莆田系医院这种不正规医院和正规医院有啥不同

### ISSUE THREAD

**Issue by GeeKmyself** [open-power-workgroup/Hospital#140]

**Comment by a1305315624** [comment]
准确的说,莆田系也是正规的医院,只是是民营医院,和其他医院相比,莆田系普遍会采用欺骗,恐吓等方式来忽悠患者去做一些没有必要的手术,吃一些没有必要的药.但也并不是所有的莆田系都会采用这样的方式.

**Comment by facetothefate** [comment]
有一种观点是 由于百度的竞价排名，导致这些医院只能挤破头靠堆钱做广告来拉客，所以羊毛长在羊身上。为了钱，或者说为了维系自己的饭碗，人什么干不出来？

风引 <notifications@github.com>于2016年5月6日周五 22:39写道：

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate

**Comment by xokctah** [comment]
本项目对莆田系医院是否正规、有何不同等问题，至少到目前为止，不作任何评论。正如我们在项目首页上所说：

> 本项目的意图是收集汇总与国内一些医疗机构有关的信息，供广大寻医问药的患者及家属参考。……我们深知自己的能力有限，因此我们只能分享我们当前所知的信息，确保我们没有捏造信息，并努力提高信息的可信度。至于这些信息应该如何指导行动，我们保持缄默。

我们相信，只要致力于消除信息的不透明与不对称，提供可获得、可验证的信息，患者和家属们自然会做出最符合他们利益的选择。我们不需要做价值评断，因为公道自在人心。
