### ISSUE TITLE
做了一个按照URL过滤的chrome插件

### ISSUE THREAD

**Issue by erichuang1994** [open-power-workgroup/Hospital#144]
https://github.com/erichuang1994/PTXNotification
不知道能不能合并进来？

**Comment by hustcc** [comment]
Chrome插件：[https://github.com/hustcc/PTHospital.chrome](https://github.com/hustcc/PTHospital.chrome)

已经发布Chrome市场：[http://hust.cc/QaDDZa](http://hust.cc/QaDDZa)

检测到网站，会自动变红，并给出医院信息：
![image](https://cloud.githubusercontent.com/assets/7856674/15013185/846859bc-1230-11e6-9eac-f7bf4040a395.png)

求合并~

**Comment by langhua9527** [comment]
都加到md文件里面了

**Comment by hustcc** [comment]
增加一个从本项目中的`README.md`文件中，解析网址信息到插件中的脚本。
[https://github.com/hustcc/PTHospital.chrome/blob/master/read_from_README.py](https://github.com/hustcc/PTHospital.chrome/blob/master/read_from_README.py)

**Comment by langhua9527** [comment]
@hustcc 用不来啊。。

**Comment by hustcc** [comment]
怎么用不来？

**Comment by hustcc** [comment]
怎么用不来？

**Comment by langhua9527** [comment]
用不来py文件，你可以介绍一个教程

**Comment by hustcc** [comment]
我这个chrome插件里面需要一个医院的js字典，就是文件[https://github.com/hustcc/PTHospital.chrome/blob/master/PTHospitalList.js](https://github.com/hustcc/PTHospital.chrome/blob/master/PTHospitalList.js)，初始数据是从你这边的readme.md文件中获取，但是手动去收集很麻烦，所以使用了一个py来解析，这样就不用手动去构造js字典了。

**Comment by langhua9527** [comment]
明白了，这个你还手动吧，因为数据不一定是准确的，暂时不提供API

**Comment by xokctah** [comment]
已在首页链接。
