### ISSUE TITLE
深圳博爱集团的就是上海沪申五官科医院，上海五官科医院在好大夫上就是上海市五官科医院

### ISSUE THREAD

**Issue by squallsun** [open-power-workgroup/Hospital#152]

**Comment by xokctah** [comment]
@squallsun 可否请你提个pull request？多谢！

**Comment by squallsun** [comment]
@xokctah 已经修改内容，并且提交了相关证据和信息。非常感谢！

**Comment by squallsun** [comment]
@xokctah 修正格式错误，提交pull request。非常感谢！

**Comment by chantisnake** [comment]
111d783432bc263d979b0a567730b63e6b57d334 已经 merge 了。如果没问题了可以关掉这个 issue 了么？

**Comment by squallsun** [comment]
Close
