### ISSUE TITLE
去中文版维基百科建个词条？

### ISSUE THREAD

**Issue by ming-ge** [open-power-workgroup/Hospital#154]

**Comment by fakeforreg** [comment]
中文维基百科上，已经有了一个“莆田系”的词条。

https://zh.wikipedia.org/wiki/%E8%8E%86%E7%94%B0%E7%B3%BB

个人建议，有维基百科编辑权限的朋友，去添加一下咱们这个项目的link，作为参考资料。

**Comment by horizon365** [comment]
挺好的想法，让历史记住这件事

**Comment by loveisbug** [comment]
维基百科不是人人都可以编辑么？添加在“概述”里还是“相关条目”里？这里拟好添加的文字内容吧。

**Comment by learningis1st** [comment]
（维基百科文章不称作“词条”，而是称作“条目”，参见：https://zh.wikipedia.org/wiki/Wikipedia:WIAA）

**Comment by fakeforreg** [comment]
@learningis1st 多谢指正

**Comment by fakeforreg** [comment]
@loveisbug 应该还是加在外部参考的link里吧。毕竟相关条目，指的是维基百科自己的条目。

**Comment by learningis1st** [comment]
参见：[WP:NOT#MIRROR](https://zh.wikipedia.org/zh-cn/Wikipedia:%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91%E4%B8%8D%E6%98%AF%E4%BB%80%E4%B9%88#.E7.BB.B4.E5.9F.BA.E7.99.BE.E7.A7.91.E4.B8.8D.E6.98.AF.E9.95.9C.E5.83.8F.E7.AB.99.E6.88.96.E8.80.85.E5.8E.9F.E5.A7.8B.E8.B3.87.E6.96.99.E5.BA.AB)

**Comment by loveisbug** [comment]
@fakeforreg “参考”是正文内容的注释吧，看到“概述”里已增加这次事件。

**Comment by chantisnake** [comment]
readme 中已经添加维基百科条目，关闭本 issue
