### ISSUE TITLE
pr 中并没有任何证据

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#159]
看了一眼写的 pr，为什么没有一个写了证据，以及开发者并没有索要证据就合并了，这样好么？

**Comment by fakeforreg** [comment]
的确存在证据不足的问题，在接下来的PR合入过程中，我们会更加认真的审查证据，并限制加入无证据的医院。

另外一些PR，是现在已有医院的补充资料，我们认为可以不必追加更多的证据。

**Comment by felixonmars** [comment]
@chantisnake 可以尝试自行取证。一些供参考的思路：https://github.com/open-power-workgroup/Hospital/issues/171

**Comment by chantisnake** [comment]
大家可以自行取证，个人认为每次 pr 还是需要有充分的证据才能 merge。

本问题已无效。关闭。
