### ISSUE TITLE
scr 是做什么的？

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#160]
里面的代码并不知道是做什么用的，看起来像是没完成的代码。而且还有 bug

**Comment by fakeforreg** [comment]
@aertoria 这个需要你解答一下。

**Comment by aertoria** [comment]
这些代码是用来自动生成一个 概览
[](https://github.com/open-power-workgroup/Hospital/blob/master/src/img/index.png?raw=true)

**Comment by aertoria** [comment]
如果有你发现有bug的话具体是？

**Comment by chantisnake** [comment]
parser 里面会把电话 parse 成医院的信息， 然后 './raw.in' 并不存在

**Comment by chantisnake** [comment]
我写了一个新的，马上写 pr，你们看看我的可不可以

**Comment by chantisnake** [comment]
https://github.com/open-power-workgroup/Hospital/pull/166

**Comment by chantisnake** [comment]
所以你这个预览的 raw data 在这个 repo 上面么？
@aertoria

**Comment by aertoria** [comment]
@chantisnake  是这样的。raw data其实就是readme。 readme的格式被改太多了所以parser可能也要改。具体的话参照img里面的那个例子

**Comment by chantisnake** [comment]
这样子。。。你觉得这个文件夹还有放在上面的必要了么？或者还是 update 一下？
@aertoria

**Comment by aertoria** [comment]
@chantisnake  因该update。 鼓励你pull request

**Comment by chantisnake** [comment]
@aertoria https://github.com/open-power-workgroup/Hospital/pull/186
这是我最新的 pr，document 有点少，明天或者周末我会添加更多的 document，你看看可不可以，在 resource/code_resource_python 里面

**Comment by chantisnake** [comment]
这个似乎已经搞清楚了，我把这个关掉了
