### ISSUE TITLE
合肥军大皮肤病治疗中心和陆军军官学院的那个医院的皮肤病治疗中心

### ISSUE THREAD

**Issue by wangxiaowang** [open-power-workgroup/Hospital#163]
#贡献指南

首先，非常感谢每一位帮助建设这个莆田系医院目录的朋友。以下投递指南，请仔细阅读：

1. issue 是用于提意见和建议的，不是用于添加医院信息的。所有的医院信息，请通过 Pull Request 方式提交。
2. 这是一个严肃认真的非商业类项目，因此在提交 Pull Request 时，请注意以下格式。
  1. 医院名称（全称）
  2. 所在地区（省、市）
  3. 负责人
  4. 网站地址（可能有多个）
  5. 联系电话（可能有多个）
  6. 证据（证据越多、越有说服力，越好！仅仅名字看起来像，是不行的！）
3. 我们会不断的清理证据不足的医院，并不断完善相关数据。

在提交正式信息前，请删除这些提示 :)

**Comment by fakeforreg** [comment]
issue不符合规范，我们会关闭。

请提交PR，谢谢
