### ISSUE TITLE
判断一个新的医院是否是莆田系的调查取证方法

### ISSUE THREAD

**Issue by felixonmars** [open-power-workgroup/Hospital#171]
以 `武汉送子鸟不孕不育医院` 为例，我进行了这样的取证：

1、已知网址 `szn027.com`，工信部 ICP 备案查询得到主体单位名为 `江西省康联投资管理有限责任公司`
截图：http://i.imgur.com/BZXZg3j.png

2、已知公司名，搜索到公司注册地址为 `江西省南昌市青云谱区井冈山大道239号`
截图：http://i.imgur.com/EfQP7Pq.png

3、已知地址，搜索得到另一所医院 `南昌市第五医院` 在同一地址
截图：http://i.imgur.com/hgzoXwt.png 

4、`南昌市第五医院` 在维基百科 “莆田系” 页面上为已知的莆田系医院（也在凤凰网最初报道中）
页面：https://zh.wikipedia.org/wiki/%E8%8E%86%E7%94%B0%E7%B3%BB
截图：http://i.imgur.com/b1fYzux.png

由此判定，`武汉送子鸟不孕不育医院` 是莆田系医院。

希望大家讨论如何记录和保存这些线索，以及指导更多贡献者来完成取证工作。

**Comment by fakeforreg** [comment]
非常棒的取证工作！

我把你的这段文字，更新到贡献指南去，谢谢！

**Comment by felixonmars** [comment]
另外，还可以通过这些信息挖出其他莆田系医院：
http://i.imgur.com/fUJaGy4.png

**Comment by Cat7373** [comment]
看到这么个新闻：http://finance.ifeng.com/a/20160505/14364975_0.shtml

**Comment by langhua9527** [comment]
@Cat7373  http://weibo.com/ttarticle/p/show?id=2309403971836839867253 你再看这个

**Comment by Cat7373** [comment]
http://finance.ifeng.com/a/20160506/14366376_0.shtml

**Comment by chantisnake** [comment]
这个已经加入 readme，不知道大家觉得这个 issue 是不是可以关掉了？

**Comment by felixonmars** [comment]
我之前建立这个 Issue 是为了抛砖引玉，希望交流更多相关经验和方法。不过看起来目前没有起到这样的作用，可以考虑关掉 :)
