### ISSUE TITLE
为什么不存一份json版本

### ISSUE THREAD

**Issue by WANG-lp** [open-power-workgroup/Hospital#181]
为什么不存一份json版本，每次commit通过json版本生成README.md?
这样比较方便程序解析，以后也方便增加更多的键值/属性

**Comment by chantisnake** [comment]
https://github.com/open-power-workgroup/Hospital/pull/182

json 今天就会写

**Comment by chantisnake** [comment]
https://github.com/chantisnake/Hospital/blob/master/resource/code_resource_python/hospital_list.json

这是我的 fork 里面的，同样还有 yaml

**Comment by chantisnake** [comment]
我稍微重构了一下代码 https://github.com/chantisnake/Hospital/blob/master/hospital_list.json

这是新网址

**Comment by chantisnake** [comment]
json 和 yaml 格式的都已经 merge 了
之后可能会更改地方，但是基本上会在很好找的地方。目前在
https://github.com/open-power-workgroup/Hospital/blob/master/hospital_list.json

**Comment by xokctah** [comment]
chantisnake非常感谢你的工作！可否请你提个pull request给本项目？

**Comment by chantisnake** [comment]
这个已经在本项目内了，在 resource/API_resouce 中，如果没有问题，这个可以删除了？

**Comment by chantisnake** [comment]
这个 issue 可以关闭了？

**Comment by chantisnake** [comment]
已经存在了，https://github.com/open-power-workgroup/Hospital/tree/master/resource/API_resource
关闭本 issue
