### ISSUE TITLE
目录中 武汉 -> 男科等不会跳转

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#185]
武汉的子目录下基本都不会跳转

**Comment by MofeLee** [comment]
因为在目录中有特殊符号，所以导致跳转有问题

**Comment by MofeLee** [comment]
已经顺手修复了~

**Comment by chantisnake** [comment]
对了那个 project.json 是必要的么？
有没有可能移到 resource folder 里面？
因为那里面是放代码的。。。

**Comment by MofeLee** [comment]
### 方案一
通过`npm install -g doctoc`全局安装`doctoc`
然后通过`doctoc README.md `来更新目录
全局安装`doctoc`就不需要`package.json`
但是不太建议这么做，因为可能其他人不知道这些命令
### 方案二
可以移动`package.json`到`resource`目录中
然后修改`package.json`为
```json
{
  "scripts": {
    "toc": "doctoc ../README.md"
  },
  "devDependencies": {
    "doctoc": "^1.0.0"
  }
}
```
不过需要在`resource`目录中运行`npm run toc`

**Comment by chantisnake** [comment]
看看其他人怎么看吧，因为我把我的 code 都移到 resource 里面了，有人跟我说 admin 觉得应该把 root 变得简单一点。

**Comment by MofeLee** [comment]
嗯，不过我觉得放根目录更好用

**Comment by chantisnake** [comment]
相关已经修复，关闭
