### ISSUE TITLE
天津区 更新资料 【天津权威医院名单】 以及 天津莆田系医院最全名单

### ISSUE THREAD

**Issue by everhopingandwaiting** [open-power-workgroup/Hospital#188]
http://mp.weixin.qq.com/s?__biz=MzA5Mzg2MDQxOQ==&mid=2664664512&idx=5&sn=d33622efcda91375debc88ce6fb32373&scene=2&srcid=0505BEL87coQp7i3jUjL6r9q&from=timeline&isappinstalled=0#wechat_redirect

**Comment by fakeforreg** [comment]
你好，这个公众号文章里，出现的10家天津医院。本项目已经收录。

从天津阿波罗医院以下的5家医院，还没有收录，能麻烦你提一个PR给我们吗？

谢谢

**Comment by everhopingandwaiting** [comment]
阔以 起床后 pull req

**Comment by everhopingandwaiting** [comment]
@fakeforreg  是否 也搞份 白名单医院🏥？

**Comment by fakeforreg** [comment]
精力不足，如果要搞，最好是另开一个新的项目。

这个项目的目标最好单一：仅仅收录莆田系医院&科室，并附带病患证言。

**Comment by everhopingandwaiting** [comment]
@fakeforreg  OK , All  my  Support
