### ISSUE TITLE
在知乎上的宣传

### ISSUE THREAD

**Issue by physixfan** [open-power-workgroup/Hospital#193]
https://www.zhihu.com/question/23539856/answer/99203886

这里有个知乎回答为此项目做宣传的 希望大家多多点赞 让更多人看到这个项目！

**Comment by xokctah** [comment]
👍

**Comment by chantisnake** [comment]
great

**Comment by xokctah** [comment]
如果大家认识一些大V，或者看到他们在知乎的答案，可以在评论中给他们提供本项目的URL，建议他们在自己的答案中推荐本项目。
