### ISSUE TITLE
Chrome 浏览器插件: 屏蔽百度搜索列表中的所有推广链接和“疑是莆田系医院”，屏蔽“疑是莆田系医院”的网站

### ISSUE THREAD

**Issue by huntbao** [open-power-workgroup/Hospital#194]
* [插件安装地址](https://chrome.google.com/webstore/detail/%E9%A5%A5%E7%8C%AA%E9%98%85%E8%AF%BB/jfckifkogfenafeakigpkjlifbkklmih)

>如果打不开安装地址，可以使用本地安装的方式:

1. 下载安装包: [https://github.com/huntbao/piggyreader/blob/master/dist.zip](https://github.com/huntbao/piggyreader/blob/master/dist.zip) 并解压

2. 打开 Chrome 浏览器, 点击右上角的设置图标(有三条横杠), 选择 "更多工具" --> "扩展程序", 勾选"开发者模式", 选择"加载已解压的扩展程序..."

3. 选择第 1 步中解压的文件夹

刷新页面即可看到安装插件后的效果

* [插件效果](https://github.com/huntbao/piggyreader/tree/master/putian)
![baidu_search_putian_1](https://cloud.githubusercontent.com/assets/996000/15063032/2d688746-1379-11e6-86fc-42b1b994d389.jpg)

**Comment by xokctah** [comment]
👍

从技术上，我建议你的插件可以使用本项目的医院名单，然后我们共同维护一份医院名单。如果你对数据格式有要求，欢迎和我们讨论，我们尽力提供满足你要求的数据格式。

**Comment by huntbao** [comment]
@xokctah 医院名单就是本项目的提取出来的，不然也不会到这里来发了。

提取的代码在这里：[https://github.com/huntbao/piggyreader/blob/master/putian/putian.js](https://github.com/huntbao/piggyreader/blob/master/putian/putian.js)

提取后的结果在这里：[https://github.com/huntbao/piggyreader/blob/master/reader/data/putian.data.js](https://github.com/huntbao/piggyreader/blob/master/reader/data/putian.data.js)

上次12306的刷票软件把 github 搞挂了，所以数据选择直接放在插件包里面。

另外，本项目的医院名单格式一直在变化，所以解析代码可能会失败，所以名单数据还是插件单独保存一份比较好，目前是打算每隔1~2天样子更新一次插件。

**Comment by xokctah** [comment]
👍
多谢！

2016-05-06 16:12 GMT+08:00 HuntBao <notifications@github.com>:

**Comment by huntbao** [comment]
更新版本至 V1.7.7， 增加对 google, bing, yahoo, 360, sogou 搜索结果列表页的屏蔽

**Comment by chantisnake** [comment]
@huntbao https://github.com/open-power-workgroup/Hospital/tree/master/resource/API_resource
我们这里已经有 json 的代码了，而且这个是大家共同维护，可以比较好的保证数据是 up to date 的。

希望可以考虑一下

**Comment by zhangjh** [comment]
针对疑似莆田系医院，插件所做的应该是给出提示告警而不是简单屏蔽之。我认为插件不能干扰用户选择的自由，况且直接屏蔽百度推广的内容可能还会存在法律风险。不知道作者怎么看

**Comment by chantisnake** [comment]
同意 @zhangjh ，如果加上继续访问按钮会更好

**Comment by huntbao** [comment]
@chantisnake 鼠标hover的时候，右上角有移除浮层的按钮的。

@zhangjh 法律方面的问题不大懂

**Comment by aertoria** [comment]
@huntbao  这个插件的源代码github在哪？

**Comment by chantisnake** [comment]
应该是这个 
https://github.com/huntbao/piggyreader

**Comment by xokctah** [comment]
已在首页添加直接链接。关闭这个issue了。
