### ISSUE TITLE
我也做了一个插件 也希望大家补充医院网站链接

### ISSUE THREAD

**Issue by Pearyman** [open-power-workgroup/Hospital#195]
[谷歌应用商店](https://chrome.google.com/webstore/detail/%E8%8E%86%E7%94%B0%E7%B3%BB%E9%BB%91%E5%BF%83%E5%8C%BB%E9%99%A2%E5%90%8D%E5%8D%95%E6%8F%92%E4%BB%B6/ieogbmijfpmdlkdifblkcgomfmonmfbc?hl=zh-CN)

**Comment by langhua9527** [comment]
请开源，直接贴开源连接

**Comment by xokctah** [comment]
👍

从技术上，我建议你的插件可以使用本项目的医院名单，然后我们共同维护一份医院名单。如果你对数据格式有要求，欢迎和我们讨论，我们尽力提供满足你要求的数据格式。
