### ISSUE TITLE
请问如何联系？有问题说可以联系，但是第一时间联系没有人处理啊！

### ISSUE THREAD

**Issue by siyecao20073** [open-power-workgroup/Hospital#197]
↖(▔▽▔)↗

**Comment by xokctah** [comment]
请问您有什么具体的问题？您可以把问题直接贴在这里，Open Power小组会尽力及时回复。

Open Power小组是一个由志愿者组成的工作组，所有的成员都有自己日常的工作，因此我们没有办法承诺回复和处理问题的时间。但我们会尽量保证所有问题在24小时内得到初步回应。希望关心我们的同志们谅解。
