### ISSUE TITLE
关于 “南京医科二附院协作医院” 的准确性

### ISSUE THREAD

**Issue by jszh** [open-power-workgroup/Hospital#198]
在地图上[搜索不到](https://www.google.com/maps/search/南京医科二附院协作医院) “南京医科二附院**协作医院**”；有以下名称的医院：
- 南京医科大学第二附属医院
- 南京医科大学第二附属医院东院整形美容中心

[南医大二附院](http://www.jsnydefy.com)是南京医科大学的附属医院，或许其整形美容中心是承包给莆田系的，也许是这里的 “协作医院”？
在东院附近一侧的路边有一个叫 “南医大二附院东院” 的公交车站（路对面没有），不知道和莆田系有没有关系。

**Comment by siyecao20073** [comment]
你好，想了解一下这个取证是怎么取的？怎么划分是莆田系的？有相关证明吗？难道关于整形的都往莆田系上扣吗？民营的就都是莆田系了吗？当我我看到“或许”、“不知道和莆田系有没有关系”时就震惊了，这样也可以？大家都靠自己的脑补来判读一件事了吗？

**Comment by xiaolongyuan** [comment]
洗地？ 
![image](https://cloud.githubusercontent.com/assets/3142363/15064017/2debdd2c-1382-11e6-8992-6a45c6ef5e9a.png)

**Comment by siyecao20073** [comment]
今天注册不代表今天才玩 。而且，这和我什么时候来有关系吗？我只是实在憋不住了，看到大家说话都是用“或许”、“可能”、“不知道”、“也许”、“据说”这种词还振振有词时，我就觉得害怕，就想起很多说话不负责的人，想起很多奇怪的谣言，想起很多网络暴力，想起很多很多相关事件罢了。大家活在一个言论自由的时代，但是，言论自由不用负责吗？我只是感叹一下，谢谢！

**Comment by xiaolongyuan** [comment]
@siyecao20073  参阅 https://github.com/open-power-workgroup/Hospital#特别申明

**Comment by jszh** [comment]
@siyecao20073 我是看到目录列表里这家医院无法在网上查到才提的 issue。我说 “或许”、“不知道和莆田系有没有关系” 是希望提供线索，供收集证据，并不代表我认为这目前是可靠的证据。我没有以此为证据提交 pull request。

**Comment by siyecao20073** [comment]
@xiaolongyuan  你是想让我看什么申明呢？这个是作者申明，“作者对信息的可用性、准确性或可靠性不作任何承诺与保证”，这个作者不保证就不保证了，我又没有说这个作者要负责，我又没有说这个作者有什么错。或许你是想说有问题可以直接联系作者让他解决问题而不要在issue里提出吗？对于作者制作这个什么名单，我非常支持。我只是不支持上面这位的说话方式罢了。

**Comment by xiaolongyuan** [comment]
我不知道你要洗地还是咋的  这个项目本来就是 提供 也许 大概 可能

**Comment by jszh** [comment]
@siyecao20073 我就是觉得列表里 “南京医科二附院协作医院” 有问题、不确切，所以提出这个 issue，可能你误解了。

**Comment by siyecao20073** [comment]
@jszh  不好意思，那是我错了。是这样的，我并没有看下面列表里关于“南京医科二附院协作医院” ，我就是点进来看到你的issue，大家提意见都是直接看到相关整形、民营什么的直接就往莆田系上靠，觉得这种方式真的很不好，不应该一头热的往热点上挤。你做的没错，是对有问题的东西提出问题和意见，不好意思。

**Comment by siyecao20073** [comment]
@xiaolongyuan  我并不想怎么样，我只是说话。也请你不要一来就把洗地的帽子扣我头上。我还是认为，说话该负责。

**Comment by jszh** [comment]
@siyecao20073 没关系，希望能提高名单真实性。

**Comment by siyecao20073** [comment]
@jszh  真的很不好意思，再次给你道歉。我也觉得真实性很重要，就怕不真实的东西影响大家。

**Comment by felixonmars** [comment]
有一定线索：
http://bayyfk.com/ryzz/show-65-549-1.html
`常州博爱医院作为南京医科大学第二附属医院技术协作单位……`

ICP 备案信息显示主体为 "常州博爱医院有限公司"
http://i.imgur.com/WWnOuzz.png

后者有被曝光记录：
http://toutiao.com/i6280482062457635330/

**Comment by xokctah** [comment]
感谢大家的支持。Open Power小组是一个由志愿者组成的工作组，所有的成员都有自己日常的工作，因此我们没有办法承诺回复和处理问题的时间。但我们会尽量保证所有问题在24小时内得到初步回应。希望关心我们的同志们谅解。

针对这个话题，非常感谢siyecao20073和jszh两位的讨论。我们正在加紧对医院列表的加工，力争进一步提高这个列表的可信度。同时，我们深知我们的能力有限，因此我们只能分享我们当前所知的信息，并确保我们没有捏造信息。至于这些信息应该如何指导行动，我们保持缄默。

也特别感谢felixonmars提供的信息。我们会跟踪这条信息。
