### ISSUE TITLE
请出示南京解放军八一医院肝病中心为莆田系的证据。

### ISSUE THREAD

**Issue by xiaowing** [open-power-workgroup/Hospital#204]
莆田系医院的名单维护者：

你们好。

南京解放军八一医院肝病中心是全军肝病中心，请出示其为莆田系的证据。

**Comment by xiaolongyuan** [comment]
南京这边稍了解的人都知道 这个被外包出去了 至于是不是莆田系 那就不得而知了

**Comment by xokctah** [comment]
@xiaowing 我们正在积极查证，谢谢您的提醒。

@xiaolongyuan 如果有更多信息请提供，多谢！

**Comment by fakeforreg** [comment]
@xiaowing

在网上，我们找到一篇声明：http://www.aidn.com.cn/2014/0424/83193.html

# 全军肝病中心郑重声明
1. 上述联系地址为解放军458医院全军肝病中心唯一联系地址，除此之外，并无分院。
2. 近期有个别医疗机构，冒充我院“全军肝病中心”的名义，进行医疗宣传等，请广大肝病患者要注意正确识别，以免给你的利益造成不必要的损失。
3. 同时也正告个别医疗机构，不要再以我院“全军肝病中心”的名义进行虚假宣传。请立即停止侵权行为，否则我单位将依法追究其侵权法律责任。 

因此，对于南京的这个全军肝病中心，我们有不少疑问，还在查证中。

**Comment by fakeforreg** [comment]
目前找到两份证据，初步可以判定《南京解放军八一医院肝病中心》，不是莆田系医院（或科室外包）。

1. 刊载于新华报业网的《[解放军八一医院发声明：网传领导“节日”支出审批表系捏造](http://js.xhby.net/system/2016/05/05/028588255.shtml)》
该网址 xhby.net，确为工信部备案网站 苏ICP备05012207号-1

2. 江苏电视台新闻中心官方微博 @江苏新闻 发布的微博：[【最全！南京“莆田系”医院名单列表大揭秘】](http://weibo.com/1301904252/Du8JUkI7N?type=comment#_rnd1462592599407) 其中并无南京解放军八一医院肝病中心。

因此，我们将删除这个医院，并对@xiaowing 表示感谢！

**Comment by xiaolongyuan** [comment]
@xiaowing 强烈反对 ！！  建议此词条列为【疑义】  ‘南京解放军八一医院肝病中心’ 明白人都知道  拿小站新闻来辟谣 癖个屁！

**Comment by xiaolongyuan** [comment]
@fakeforreg

**Comment by fakeforreg** [comment]
@xiaolongyuan 请给出你的进一步的证据，如果证据可靠，我们会将这个医院放回去。

**Comment by xiaolongyuan** [comment]
@fakeforreg  之前爆过朋友圈  秒删  我只能说根据“流言” “这个单位每个月有任务指标” 

因上  我并没有直接证据证明   但是 还是希望有人有进一步的内部消息透出
