### ISSUE TITLE
医院数据格式要求

### ISSUE THREAD

**Issue by hustcc** [open-power-workgroup/Hospital#209]
希望能够提供这样的数据结构：
```
“医院网址”: ["医院名称", "医院电话", "其他信息，没有可以为空"],
```

是一个js的字典形式。

用于项：目[https://github.com/hustcc/PTHospital.chrome](https://github.com/hustcc/PTHospital.chrome)，`目前项目在trending上`，使用人还比较多，迫切希望完善。

希望能能有这样的数据，这样插件就可以统一使用一个项目的数据，数据统一准确。

**另外**，希望项目[PTHospital.chrome](https://github.com/hustcc/PTHospital.chrome)能够得到项目的`特别推荐`，目前在github的trending上，应该是最受欢迎的一个插件，数据也保持和这边同步，并且项目开始ci，提交之后自动同步到cdn，并更新到插件上。

**Comment by xokctah** [comment]
@hustcc 收到你的请求。有个困难在于，很多医院没有网址信息。如果用一个数字ID你觉得如何？例如：

```
{
  "hospitals": [
    1: {
      "name": "xxxx医院",
      "url": "http://www.xxx.com",
      "phone": "xxxxxxxx"
    }, 
    2: {
      ...
    }
  ]
}
```

**Comment by hustcc** [comment]
可以的，非常感谢，只要是格式化数据即可

**Comment by chantisnake** [comment]
https://github.com/open-power-workgroup/Hospital/tree/master/resource/API_resource
@hustcc 
不知道这是不是你要的格式

**Comment by hustcc** [comment]
这个格式可以的，只要是格式化的数据就可以了。

我这边项目已经按照这个json格式自动更新线上chrome版本的数据，每一小时和这边同步一次，希望能够保证json格式稳定不变。

如果有变化，希望能通知一下我们，感谢~

**Comment by fakeforreg** [comment]
@hustcc 我建议还是：在你那边提交医院数据的用户，引导他们在这个项目来提交数据。而你的项目，是纯粹的数据使用者。

你觉得如何？

**Comment by hustcc** [comment]
提交数据需要经过严格审核，不然误杀就不太好了，所以建议将数据的审核统一做，当然如果我这边做本身没有什么问题，加一个后台，然后需要一个团队来做审核工作。
对于非盈利来说，还是需要时间和成本的。

**Comment by chantisnake** [comment]
@hustcc 这个已经实现是不是可以关掉了？
还有，有一个开发者的帖子，希望你可以留言加入，这样我们就可以及时通知你 api 变动
https://github.com/open-power-workgroup/Hospital/issues/223

**Comment by zhangjh** [comment]
建议增加city字段，我的插件支持按城市检索。

**Comment by chantisnake** [comment]
@zhangjh 可不可以更具体一点？json 的城市就是最高级的 key 啊

**Comment by zhangjh** [comment]
哦 刚没看代码文件，以为是issue里面的格式，源码格式字段ok的

**Comment by chantisnake** [comment]
@zhangjh 这个确实，因为是从 readme 中直接提取出来的 key，python 能很好的处理这种东西，但是其他很多语言都不行，这也让我很苦恼，我们最近在试图采用一种新的数据结构。正在重构 project 中。

**Comment by chantisnake** [comment]
@zhangjh https://github.com/open-power-workgroup/Hospital/blob/master/data/example.yml
这是新的数据结构
