### ISSUE TITLE
请问没有网站的医院要提供什么证明？

### ISSUE THREAD

**Issue by waitingHao** [open-power-workgroup/Hospital#212]
如题，知道一些仁爱医院，但网上没有太多信息。

**Comment by xokctah** [comment]
@waitingHao 感谢你的关注。我们希望列出的医院符合以下几项条件中的至少一项：

- 曾经投放百度竞价广告 
- 曾经媒体报道过医疗纠纷或者受骗
- 确认是莆田系

证据的来源可能包括（但不限于）以下几种：

1. 公众信息平台的查询信息；
1. 新闻媒体的报道；
1. 网站或论坛上的信息。

这些信息源的可信度会有所不同，我们会根据不同的信息源加以分类。不过，只要你认为有可信度的信息线索，都欢迎提供。
