### ISSUE TITLE
做了一个GM脚本

### ISSUE THREAD

**Issue by sylingd** [open-power-workgroup/Hospital#213]
# 科普内容
GM脚本：为GreaseMonkey脚本的简称

GreaseMonkey：一款可以在网页上运行JS脚本的Firefox扩展

适用范围：任何安装了GreaseMonkey/TamperMonkey（或类似插件）的浏览器

此扩展/插件安装范围十方广泛，仅Firefox平台通过官方途径的安装量就已达到一百多万。支持的浏览器也众多，任何以Gecko（代表：Firefox）Webkit（代表：Chrome、各种国产套壳浏览器）均有对应的插件

不同于扩展，GM脚本不需要浏览器安装新的扩展，并且占用更小、维护更方便

# 安装

脚本名称：Putian Warning

[安装](http://firefoxbar.github.io/#userscripts)

# 截图

![648905d7912397dd35876af25e82b2b7d2a287ff jpg](https://cloud.githubusercontent.com/assets/5326684/15075043/f742b0f4-13d4-11e6-92f7-59d2f7e9222f.png)

**Comment by xokctah** [comment]
👍

一起加油！

**Comment by xokctah** [comment]
在首页上加了直接链接。关闭这个issue。

**Comment by BROBIRD** [comment]
@sylingd 建议加上`// @exclude http://127.0.0.1:*/*` 不然访问本地会有问题……

**Comment by sylingd** [comment]
@BROBIRD 感谢提醒，稍后解决此问题

**Comment by sylingd** [comment]
@xokctah 咳咳，不只用于Firefox。实际上TamperMonkey在Chrome上的用户量也很庞大

**Comment by BROBIRD** [comment]
@sylingd 主要是还要开着ZeroNet更新ss……
