### ISSUE TITLE
基于本 repo 的 iOS app

### ISSUE THREAD

**Issue by MQL9011** [open-power-workgroup/Hospital#216]
我看到现在有JS文件，如果有网络接口就好了，方便直接网络请求，时时刷新。
这是我写的iOS端的代码https://github.com/MQL9011/Hospital_PTX.git
写的比较简陋~

**Comment by MQL9011** [comment]
感谢。

**Comment by maneesiamamulet** [comment]
Good

**Comment by maneesiamamulet** [comment]
Good

**Comment by maneesiamamulet** [comment]
Good

**Comment by lindazhang102** [comment]
这个好，建议快快实现

**Comment by lizy14** [comment]
@MQL9011 
https://raw.githubusercontent.com/open-power-workgroup/Hospital/master/resource/API_resource/hospital_list.json

**Comment by xokctah** [comment]
谢谢 @MQL9011 提出的要求，谢谢 @lizy14 提供的临时解决方案。我们正在梳理数据格式，随后会采用新的数据格式来呈现数据，并考虑如何更好地host内容（包括网页和JSON格式）。请大家理解并保持关注。

**Comment by chantisnake** [comment]
原来的标题已经不适用了，更改了新标题，如果觉得不妥可以改回来
