### ISSUE TITLE
能不能教一下怎么分别该院或者该科室是不是莆田系或者私人承包的？

### ISSUE THREAD

**Issue by laijuncheng** [open-power-workgroup/Hospital#22]
这样广大网友才能更好的分别和更新

**Comment by jincdream** [comment]
我建议可以給每家已经开个XXX.md ，用来记录某家医院的详细信息。包括莆田系相关的信息。 没人搜一家医院基本就能很快完善了。~

**Comment by laijuncheng** [comment]
@jincdream 我相信大部分网友都无法正确识别是不是莆田的（包括我），因为这种事情我们不是专业的，就怕被误伤，我相信虽然正规医院有可能会很贵，但是不会害命

**Comment by cxz1998** [comment]
这个只能等更进一步爆料了

**Comment by a1305315624** [comment]
最好各位能找本地的医学界的人士查证,一般这些人会比较了解当地医院哪些是莆田系哪些是私人承包.并且声誉如何.

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate
