### ISSUE TITLE
有没有人愿意帮这些人写一下 pr

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#227]
我看见 issue 中有很多人写了一些医院。其中大部分医院都没有加进去。

有些人不了解 GitHub，不知道怎么 fork 写 pr，不知道我们组织的成员或者其他人愿意负责清理这些 issue？
把一些有明确证据的先写 pr 提交了，证据不明确的可以在 issue 中索要更多证据，也可以自己查询

这一类 issue 在这里：
https://github.com/open-power-workgroup/Hospital/issues?q=is%3Aissue+is%3Aopen+label%3A%22data+contribution%22

**Comment by xokctah** [comment]
收到。等数据格式一确定就着手处理。
