### ISSUE TITLE
请问你们gh_pages下面的内容能否被复制使用

### ISSUE THREAD

**Issue by wangqiliang** [open-power-workgroup/Hospital#234]
我想参考你们在gh_pages下的源代码，利用该项目提供的信息，做一个莆田系医院的查询网站。请问这么做是否允许，谢谢。

**Comment by HuanMeng0** [comment]
https://github.com/open-power-workgroup/Hospital/issues/224
https://github.com/open-power-workgroup/Hospital/issues/223

**Comment by wangqiliang** [comment]
@HuanMeng0 Thanks.
Close #234
