### ISSUE TITLE
update.py输出问题

### ISSUE THREAD

**Issue by HuanMeng0** [open-power-workgroup/Hospital#238]
我的项目必须要挂cron保持json数据的及时更新
但是不知道为什么update.py会输出需要转换的文字，导致cron无法正常执行
![image.png](https://ooo.0o0.ooo/2016/05/08/572eef150f0f9.png)

**Comment by chantisnake** [comment]
https://github.com/open-power-workgroup/Hospital/issues/226

因为这个报错。我会起床修复

**Comment by chantisnake** [comment]
个人建议不要使用 update.py，最好直接使用转化成功的数据。

只是个人建议，因为有时候 update.py 有 bug（可能是因为更改了 readme 的格式之类的问题） update.py 没及时修改的话会造成错误。

但是如果有错的话 json 和 yaml 就不会更新，虽然数据会有一点 outdated，但是不会造成 bug

**Comment by HuanMeng0** [comment]
希望尽快修复

**Comment by chantisnake** [comment]
@HuanMeng0 应该已经修复了，你试试，如果没有问题可以关闭这个 issue 了

**Comment by HuanMeng0** [comment]
THX

**Comment by chantisnake** [comment]
如果之后有 bug 仍然会输出该行，你觉得可以么？@HuanMeng0

**Comment by HuanMeng0** [comment]
能让cron正常运行update.py即可

**Comment by HuanMeng0** [comment]
目前又遇到了个bug
```
run in normal mode
we cannot recognize the type of the line
here is some information you can send to the issue:
    this is the line
    '          (3) http://imgur.com/PdDIwHo'
    previous line has type index: 2
    here is the indentation list: [0, 1, 9]
    current line has 10 leading white spaces
press <enter> to continue
```
不能忽略错误吗？

**Comment by chantisnake** [comment]
。。。我 implement 一下

**Comment by chantisnake** [comment]
@HuanMeng0 应该好了，用 `python update.py --silent` 就可以了

**Comment by HuanMeng0** [comment]
THX
