### ISSUE TITLE
data 文件夹是干什么的？

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#247]
@san577478 是你做的 data 文件夹么？请问你准备如何维护这个文件夹，以及这个文件夹和 `resource/api_resource` 文件夹的区别在哪里？

**Comment by xokctah** [comment]
我们计划用这个目录来提交医院相关信息，然后基于这些数据（YAML格式）生成JSON API和网页。请稍候，现有数据转到新格式的工作马上就会启动。

**Comment by chantisnake** [comment]
嗯，我觉得是可以得，如果要现有格式转换我说不定可以帮上忙。我觉得只要把 yaml writer 小改一下就能改成那个格式
