### ISSUE TITLE
非程序员不会RP

### ISSUE THREAD

**Issue by mvc3698** [open-power-workgroup/Hospital#256]
首先，非常感谢发起与维护这个项目的热心人。
但是，我不是一位程序员，来GH也只是下载项目来使用而已。现在看到这个项目也想尽一份绵薄之力，但是实在是不知道“你的PR可能存在分支选择上的错误。应该是从你自己的仓库分支，发起PR到我们这个项目的incoming分支。请再试一次。”里的“分支”、“仓库”之类的是什么。可能大家都已经默认了来这里的是程序员吧。

**Comment by fakeforreg** [comment]
@mvc3698  非常抱歉。首先应该感谢您的贡献，其次，我可以帮助您将信息提交到项目中去。

如果您愿意尝试按照程序员的方式，来提交信息的话，也可以参考一个简单的文档：
http://www.worldhello.net/gotgithub/04-work-with-others/010-fork-and-pull.html#fork

对这份文档，如果有不了解的地方，也欢迎随时来找我们。

**Comment by fakeforreg** [comment]
信息已经查证，广西柳州丽人医院，已经加入。
