### ISSUE TITLE
希望将hustcc/PTHospital.chrome在README中单独一行列出

### ISSUE THREAD

**Issue by hustcc** [open-power-workgroup/Hospital#261]
# chrome插件

建议将[hustcc/PTHospital.chrome](https://github.com/hustcc/PTHospital.chrome)在README中单独一行列出，这个插件是最早的一个开源项目，且是目前chrome商店用户最多的插件，各种网络报道的也是这个插件[搜索链接](https://www.google.com.hk/search?q=%E8%8E%86%E7%94%B0%E7%B3%BB%E7%BD%91%E7%AB%99%E6%8F%90%E9%86%92%E6%8F%92%E4%BB%B6&oq=%E8%8E%86%E7%94%B0%E7%B3%BB%E7%BD%91%E7%AB%99%E6%8F%90%E9%86%92%E6%8F%92%E4%BB%B6&aqs=chrome..69i57j69i65j69i60l2&sourceid=chrome&ie=UTF-8)，且star最多，上过trending首页，目前在js 周trending上，插件完全使用本项目数据，其他插件关注度比较小，也没有更新维护。

![image](https://cloud.githubusercontent.com/assets/7856674/15135831/5a5398a4-16ad-11e6-9d1d-6e9d092697d5.png)

目前有部分医院针对`这个插件做屏蔽手段`，希望能让更多人看到项目，并且积极的参入到这个插件的开发中，而不是一系列的轮子而没有人维护。

**Comment by binarywang** [comment]
居然有此事，这种医院真可恶

**Comment by hustcc** [comment]
@binarywang https://github.com/hustcc/PTHospital.chrome/blob/master/ChangeLog.md 看这个，我准备对这额屏蔽插件的医院给暴漏出来~
