### ISSUE TITLE
小打小闹

### ISSUE THREAD

**Issue by mixlan123** [open-power-workgroup/Hospital#262]
莆田系医院 太多，他们有自己的协会。直接去查协会资料可以否？ 
莆田系医院 这是一个抱团的组织.  感觉这样没办法追究任何东西.  也不能纠正什么.

参考:
莆田(中国)健康产业总会

http://health.huanqiu.com/healthindustry/2015-04/6110177.html

http://baike.baidu.com/link?url=2iuhoTPT_WOT1A30BnI7FCg41CfsQBy_484ZykTD_Q-dhjhwe6Fmk12Q7cllSFt32_uNQS2JszJynFla-igU3a

**Comment by fakeforreg** [comment]
你给出的这两个链接里，并没有莆田系医院的信息。

这个issue关闭了。
