### ISSUE TITLE
上海医院中的 done 是谁添加的？

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#281]
上海有一部分医院后面有 [done] 这个标签，请问这个标签是什么意思？

**Comment by zhuangbiaowei** [comment]
我们正在做新的数据格式，每个医院的数据完成后，会标一个done。

目前的数据在这里可以查看：  https://github.com/open-power-workgroup/Hospital/tree/incoming/data

**Comment by GithubOpenPowerProgrammer** [comment]
是我添加的，表示已经添加到新的数据里面了

**Comment by chantisnake** [comment]
这样，可以试试先机器转换然后再微调。。。

问一下 uuid 是用医院名生成的 hash 还是随机的？
