### ISSUE TITLE
update.py再次出现问题

### ISSUE THREAD

**Issue by HuanMeng0** [open-power-workgroup/Hospital#291]
因为README.md的格式错误，导致转换出错，需要按ENTER以继续
![0.png](https://ooo.0o0.ooo/2016/05/12/5735164e7747f.png)

**Comment by chantisnake** [comment]
谢谢。。。现在的格式实在太烦人了，我们会尽快解决的

**Comment by ccding** [comment]
I'd suggest you to store data into a formatted file (e.g., json, xml), and generate README.md from there.

**Comment by chantisnake** [comment]
我们现在在做这个，看这里 https://github.com/open-power-workgroup/Hospital/tree/incoming/data
