### ISSUE TITLE
在没有完全迁移数据的情况下直接删除之前数据是不是有些不妥？

### ISSUE THREAD

**Issue by chantisnake** [open-power-workgroup/Hospital#309]
这样其他人的 app 不都直接挂了么。。。

**Comment by xokctah** [comment]
@chantisnake sorry！我以为其他人的app现在都有了自己的一份json数据，README.md里面的数据又没有更新，已经不需要了。不好意思，冒失了。

请问其他人的app原本是怎么使用README.md里的数据的？是否需要README.md的医院列表？是否还需要update.py及其依赖库？

或者我建议一个方案：你是否可以在 https://github.com/open-power-workgroup/Hospital/blob/15b991ec639bc5ec1f086282df62f1488d142262/README.md 这个版本的基础上跑出一份json数据，然后直接提交这个json数据文件，你看这个方法可行不？

**Comment by chantisnake** [comment]
我建议可以建一个 backward compatible branch，之后放入 json 和 yaml 以及 readme 数据（我不确定有人还在用 readme 的数据），然后对这个 branch 不再更新。

然后放出公告告诉数据结构的迁移。因为有些 app 可能会通过 web request 来获得 json 文件。而不是存在本地的。

而且现在数据迁移不完全，就算完全了也应该给其他开发者一个转换的时间。

**Comment by xokctah** [comment]
好的。刚才我已经做了一个完整恢复，把README的数据、JSON和YAML、以及update.py及其依赖全都恢复到master了。稍后再来做调整。

**Comment by chantisnake** [comment]
谢谢
