### ISSUE TITLE
提个醒，凤凰网的名单并不完全可信，有误伤可能

### ISSUE THREAD

**Issue by HorseLuke** [open-power-workgroup/Hospital#32]
凤凰网的专题在朋友圈有转发后就有留意了，但查询后发现似乎不对劲，本地有间正常的公立医院也在名单上了，现在正在找人核实中。（20160503 1506更新：确定误伤，已pull request删除）

在顶着安眠药的药效后，找了一下，凤凰网的真正来源似乎是13年或更早的的“莆田系医疗领袖名录”，个人觉得，这份东西的可信度不高：http://www.ptfish.com/thread-731956-1-1.html 。

PS：凤凰网将名单来源又改成“第一财经”了，这个来源越发有问题了。作为新闻媒体，应有核实名单真实性的义务。新闻媒体这样趁热点，真是颇可恶。

**Comment by liujianhei** [comment]
上海五官科医院应该是误伤吧

**Comment by HorseLuke** [comment]
@liujianhei 我不是上海人，根据性感玉米的微博评论，"复旦大学附属眼耳鼻喉科医院，民间俗称五官科医院"（http://weibo.com/1676582524/DtMClkOI5 ），还有一条上海媒体也说了这事：http://weibo.com/1845864154/DtMPb7QSw 。可能是莆田系冒用名称导致的误伤。

**Comment by langhua9527** [comment]
已经修改成为 上海沪申五官科医院

**Comment by shenwei356** [comment]
三军医大学重庆新桥医院也冤枉啊，哎

**Comment by HorseLuke** [comment]
@shenwei356 建议开个issue或者pull request？看你的简介，可以说明一下。

**Comment by HorseLuke** [comment]
网传名单中误伤的医院：

  - 第三军医大学重庆新桥医院：https://github.com/langhua9527/BlackheartedHospital/pull/51

  - 东莞常平医院：http://www.cprmyy.com/page/iview.asp?KeyID=dtinf-2016-53-DBVE.447HH

备注：此处删除的依据是东莞市常平人民医院（简称东莞市常平医院，但有不少媒体又进一步简称为“东莞常平医院”）的公告。有人认为没有“市”字就是莆田医院，但实际上这个理解并不准确。考虑到本词过于宽泛，对该区医院无差别误伤，故删除为妥，以免引起医疗纠纷。

**Comment by xudn272** [comment]
北京国际医疗中心也是被误伤的，官网上有声明。

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate

**Comment by wangqiliang** [comment]
@liujianhei
@HorseLuke
我经常去复旦大学附属言耳鼻喉科医院，同时就是上海市五官科医院。绝对误伤。
不带市字的“上海五官科医院”才是莆田系。
