### ISSUE TITLE
以下名单，查询是否莆田系医院

### ISSUE THREAD

**Issue by jazy1982** [open-power-workgroup/Hospital#332]
肇庆西江医院

广州东大肛肠医院

**Comment by jazy1982** [comment]
肇庆西江医院

网址：http://www.0758120.com/

地址：广东省肇庆市端州区西江北路37号

广州东大肛肠医院

网址：http://pc.120gc.net/

地址：广州市越秀区德政中路356号（地铁农讲所A出口对面）

广州男科医院

网址：http://www.males120.com/

地址：广州市广州大道中345号中山一立交桥西南侧

**Comment by fakeforreg** [comment]
@jazy1982

在我们的数据库，只能提供一些旁证，尚未有确凿的证据

肇庆西江医院

url|icp|org
---|---|---
www.zzgkyy120.com|京ICP备13037485号|北京智慧东方文化传播有限公司
www.zqsgyy.com|京ICP备13037485号|北京智慧东方文化传播有限公司
www.zqxj120.com|京ICP备13037485号|北京智慧东方文化传播有限公司
www.zqgkyy.com|蜀ICP备14021772号|马沂楠
www.zqxjfk.cn|京ICP备13042036号|北京华夏天工网络技术有限公司
www.xjbaby120.cn|京ICP备13037485号|北京智慧东方文化传播有限公司


广州男科医院

url|icp|org
---|---|---
www.males120.cn|粤ICP备09080470号|广州男科医院有限公司
www.males120.com|粤ICP备09080470号|广州男科医院有限公司
www.gznk020.com|粤ICP备09080470号|广州男科医院有限公司
www.gznkyy.com|粤ICP备09080470号|广州男科医院有限公司
www.nanke020.com|粤ICP备09080470号|广州男科医院有限公司
www.guangzhounankeyiyuan.cn|粤ICP备09080470号|广州男科医院有限公司
www.males120.net|粤ICP备09080470号|广州男科医院有限公司
www.qlxinfo.com|粤ICP备09080470号|广州男科医院有限公司
www.81558888.net|粤ICP备09080470号|广州男科医院有限公司
www.nxbyzt.com|粤ICP备09080470号|广州男科医院有限公司
www.nanke020.net|粤ICP备09080470号|广州男科医院有限公司
www.guangzhounankeyiyuan.com|粤ICP备09080470号|广州男科医院有限公司


另外，《广州东大肛肠医院》，几乎可以确认是莆田系的，因为所有东大肛肠医院，都隶属于同一个莆田系医疗集团。

**Comment by jazy1982** [comment]
我安装了关联项目中的Chome插件，上面提示广州男科医院和肇庆西江医院为莆田系医院

**Comment by fakeforreg** [comment]
@jazy1982 

这是一个数据解读的问题，我们目前只是列出已知医院的各种证据。

但是，可能会被其他的插件，做另外的解读。

这也是我们定义了《OPW开放数据使用授权协议》的原因。

https://github.com/open-power-workgroup/Hospital/blob/master/open_data_usage_license.md
