### ISSUE TITLE
最新发现如何查找百度推广的医疗网站

### ISSUE THREAD

**Issue by fengixng** [open-power-workgroup/Hospital#333]
在百度搜索中用医院名字或网址+V或者@v，可以查看详细信息，包括
机构类型，网站地址，网站名称，备案编号，经营范围
其中最重要的是网站地址和医疗范围，可以查看这个医院的所有网址，和这个医院的医疗机构执业许可证

希望这个方法可以加入贡献者指南

**Comment by fakeforreg** [comment]
可以呀，你可以直接提一个Pull Request的。

**Comment by wangqiliang** [comment]
#335
