### ISSUE TITLE
云南中医肠胃病医院--莆田系医院

### ISSUE THREAD

**Issue by zhaochan** [open-power-workgroup/Hospital#343]
1. 医院名称（全称）：云南中医肠胃病医院
  2. 所在地区（省、市）：云南省昆明市五华区圆通街26号
  3. 负责人：朱争鸣、陈刚、连明国、张少峰（主要负责人不是很清楚）
  4. 网站地址（可能有多个）：http://www.kmwcb.cn/index.html
                                http://www.zywczk.com/a/jixingweiyan/2016/1230/211.html
                                http://www.yngcbyy.com/a/yiyuanjianjie/
                               http://www.yngcbyy.com/a/jixingweiyan/
                               http://m.67368899.com/index.html
    之前可以在百度上很多这个一医院的网址，现在都基本百度不到了，这些网址是我谷歌上搜索到的

  5. 联系电话（可能有多个）：0871-68339233
  6. 证据（证据越多、越有说服力，越好！仅仅名字看起来像，是不行的！）：
    证据一：我自己的一个亲人去这个医院看病，被坑了很多的钱；就是做了一次小手术，手术没有做好，没有做成功，留下了很大的后遗症（这是转到其他医院检查时才发现的），而且在这个医院中被迫开了很多没有用的药，这个医院不但治不好病而且还很坑人
 证据二：在大众点评上有好些关于这个医院的差评，http://www.dianping.com/shop/27249532
 证据三：之前在天涯论坛上看到过有人报道这家医院的一些不要脸、没有道德的医疗的行为，现在这个帖子不知是什么原因，找到了好像是被删了，之前看到这个帖子是在昆明板块上
 证据四：之前这个医院有百度推广，随便一搜这个医院的名字，都有很多关于这个医院的推广和广告，现在去百度搜，基本都找不到了
证据五：从名字也可以看得出来，这么好的、霸气的名字主要就是为了吸引人吧，其实医疗、医德很差

**Comment by fakeforreg** [comment]
多谢，已经加入
