### ISSUE TITLE
名单中存在错误

### ISSUE THREAD

**Issue by aleng-zhang** [open-power-workgroup/Hospital#345]
1. 武进为江苏常州市的一个区
2. 巢湖并入了合肥
3. 成都名录下绵阳玛利亚妇产儿童医院以为成都玛利亚妇产儿童医院
4. 启东市属于江苏南通
5. 南宁存在重复
6. 伊宁为新疆伊犁州的一个市
[个人修改版本](https://github.com/aleng-zhang/aleng-zhang.github.io/blob/master/_posts/2017-07-09-%E8%8E%86%E7%94%B0%E7%B3%BB%E5%8C%BB%E9%99%A2%E5%90%8D%E5%BD%95.md)
可能违反了你们使用协定的第二条，希望能获得授权

**Comment by aertoria** [comment]
Just go and do a pull request
