### ISSUE TITLE
为什么北京的几个武警医院没有入列

### ISSUE THREAD

**Issue by laole918** [open-power-workgroup/Hospital#35]
莆田系只是指私人医院，不包括科室被私人承包吗？
我曾经在武警三院治疗过，发现有些不对就转到其他医院，其他医院的医生在提及三院时，有的怕担责任避而不谈，有的医生比较直接，不过言语间都能感觉到三院属私人承包，使用过时技术，半真半假来欺骗患者。

**Comment by langhua9527** [comment]
有没有媒体的报道，给个连结，然后你提交上来

**Comment by ibelem** [comment]
尤其是 中国人民武装警察部队北京市总队第二医院 

引用凤凰网： 在朋友圈热门文章《一个死在百度和部队医院之手的年轻人》中，作者通过检索自称“武警北京总队二院官网”的域名注册信息，发现魏则西曾经就医的武警北京总队二院肿瘤生物中心，其背景是莆田系。而在1月“血友病贴吧事件”中，当时媒体对部分已售出的疾病贴吧进行调查，其中承包甲亢吧的是所谓“武警北京总队医院中医甲状腺科”。
http://news.ifeng.com/a/20160501/48651671_0.shtml

**Comment by xokctah** [comment]
已收入武警北京总队二院和武警北京总队医院两条数据。多谢。
