### ISSUE TITLE
如何评判一家医院是不是黑医院？

### ISSUE THREAD

**Issue by bluicezhen** [open-power-workgroup/Hospital#4]
如何评判一家医院是不是黑医院？不能是您一句话就把医院黑了吧！

**Comment by langhua9527** [comment]
https://www.zhihu.com/question/21931701

**Comment by zhen639** [comment]
所以，名单上列的这些医院都是遵循了知乎的标准被划分为black hearted hospital了？

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate

**Comment by xokctah** [comment]
见项目首页：

> 进入这份名单的医院符合以下三个条件中的至少一个：
> 

- > 曾经投放百度竞价广告
- > 曾经被媒体报道过医疗欺诈事件
- > 与莆田系存在直接关系

本项目已废弃使用“黑医院”的说法。现在项目意图是：

> 收集汇总与国内一些医疗机构有关的信息，供广大寻医问药的患者及家属参考。

谢谢 @bluicezhen 提出。
