### ISSUE TITLE
建议增加一个文档专门定义莆田系的评判标准

### ISSUE THREAD

**Issue by aertoria** [open-power-workgroup/Hospital#47]
建议增加一个文档专门定义莆田系的评判标准

**Comment by langhua9527** [comment]
这个标准很难判断，不是莆田系的医院也有很多像莆田系这样的经营

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate
