### ISSUE TITLE
怎么证真伪

### ISSUE THREAD

**Issue by ScorpioNeal** [open-power-workgroup/Hospital#50]
附加个链接这样类似的证据也好啊

**Comment by langhua9527** [comment]
公开的数据，有问题立刻修改，这个也不是保证绝对正确的，但是发现的问题越多，错误就越少

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate
