### ISSUE TITLE
建议把各医院的地址也贴上来

### ISSUE THREAD

**Issue by code-artisan** [open-power-workgroup/Hospital#64]
如题！个人觉得这样会更醒目，记名字可能容易忘，图形化的界面会让人加深影响，仅代表个人观点。。。

**Comment by langhua9527** [comment]
已经有人做了一个地图的了

**Comment by code-artisan** [comment]
牛逼 💯

**Comment by chantisnake** [comment]
https://github.com/open-power-workgroup/Hospital/issues/136

我认为这两个 issue 基本是一样的
