### ISSUE TITLE
数据有效性和真实性

### ISSUE THREAD

**Issue by everhopingandwaiting** [open-power-workgroup/Hospital#78]
@langhua9527  作为发起者我觉得,你的责任还是蛮多,毕竟鱼龙混杂,更多甄别真假数据的责任在你了!

**Comment by langhua9527** [comment]
对，数据真实性需要大家一起努力，如果有发现有问题的数据，提交上来，马上修改。这是一份公开的数据，有问题，谁都可以来修改，改的次数越多，错误就会越少

**Comment by t-k-** [comment]
@langhua9527 建议按照 #112 所说必须提供出处和判断依据才能进行 merge，这样会更可信一些。每个人都可能成为百度。

**Comment by feng99** [comment]
支持发起者.

**Comment by chantisnake** [comment]
我觉得现在每次 pr 应该要有充分的证据才能 merge

**Comment by chantisnake** [comment]
询问莆田系特点
https://github.com/open-power-workgroup/Hospital/issues/140
https://github.com/open-power-workgroup/Hospital/issues/119
https://github.com/open-power-workgroup/Hospital/issues/47
https://github.com/open-power-workgroup/Hospital/issues/22

询问数据真实有效性
https://github.com/open-power-workgroup/Hospital/issues/78
https://github.com/open-power-workgroup/Hospital/issues/50
https://github.com/open-power-workgroup/Hospital/issues/32
https://github.com/open-power-workgroup/Hospital/issues/4

将这个 issue 列为 duplicate
