### ISSUE TITLE
根据凤凰网的那个h5页面获取了莆田系医院的数据并简单可视化展示了一下

### ISSUE THREAD

**Issue by wandergis** [open-power-workgroup/Hospital#81]
- github地址 https://github.com/wandergis/putian-hospitals
- 截图
![screenshot](https://cloud.githubusercontent.com/assets/5799374/14980810/929ba850-115d-11e6-8d37-6e03f3916ed1.png)

**Comment by langhua9527** [comment]
感谢，我会马上加进去，但是你直接用人家的JS的文件，那个里面的内容没有办法更新

**Comment by wandergis** [comment]
嗯，我后期会根据这个你的这个仓库的结果来作为我的数据源。

**Comment by langhua9527** [comment]
现在显示不出来了，是不是那个凤凰网的JS文件引入不了

**Comment by wandergis** [comment]
我这边查看是ok的呀，你打开你的浏览器的控制台看是否报错了？我好排查。

**Comment by chchuj** [comment]
能导一份到google自定义地图吗？

**Comment by wandergis** [comment]
你指的是这种吗 https://drive.google.com/open?id=1vrqLv1xiIb76gqrbdzMH11AsMA0&usp=sharing

![image](https://cloud.githubusercontent.com/assets/5799374/14981579/a318052a-1162-11e6-9417-de1c5884d50f.png)

**Comment by chantisnake** [comment]
如果可以的话希望可以基于这个 repo
这里有 json 和 yaml 文件：
https://github.com/open-power-workgroup/Hospital/tree/master/resource/API_resource

**Comment by wandergis** [comment]
好的，我回去之后修改

**Comment by xokctah** [comment]
首页已有链接，close this issue
