### ISSUE TITLE
做了款Android版莆田系医院搜索

### ISSUE THREAD

**Issue by shixinzhang** [open-power-workgroup/Hospital#87]
如题，小程序猿别的也做不了，看到这个后2个小时写了Android版黑心医院搜索App，具体介绍在 

github： https://github.com/shixinzhang/BlackheartedHospitalApp

数据还不太多，正在从你这里导出，谢谢了！

**Comment by langhua9527** [comment]
最好有网页版，APP版的不推荐的

**Comment by shixinzhang** [comment]
好吧，表示理解。我有个不情之请，你可不可以给我一个star，那样我就不至于觉得白做了。Σ(っ °Д °;)っ

**Comment by langhua9527** [comment]
已star
