### ISSUE TITLE
根据此处的数据做了个谷歌插件，支持按城市查找并且

### ISSUE THREAD

**Issue by zhangjh** [open-power-workgroup/Hospital#94]
如果通过搜索引擎误入莆田系网站，会弹出告警提示

项目开源在：[点击查看](https://github.com/zhangjh/chromeExt/blob/master/%E8%8E%86%E7%94%B0%E7%B3%BB%E5%8C%BB%E9%99%A2%E6%A3%80%E6%B5%8B%E5%99%A8/README.md)

**Comment by langhua9527** [comment]
OS 下面的chrome是安装不了的

**Comment by zhangjh** [comment]
@langhua9527  不用mac，为什么安装不了？

**Comment by hustcc** [comment]
Chrome插件：[https://github.com/hustcc/PTHospital.chrome](https://github.com/hustcc/PTHospital.chrome)

已经发布Chrome市场：[http://hust.cc/QaDDZa](http://hust.cc/QaDDZa)

检测到网站，会自动变红，并给出医院信息：
![image](https://cloud.githubusercontent.com/assets/7856674/15013185/846859bc-1230-11e6-9eac-f7bf4040a395.png)

贡献代码很容易，只需要修改医院List即可，求合并~

**Comment by chantisnake** [comment]
我们希望基于本项目的插件开源。
https://github.com/open-power-workgroup/Hospital/issues/224

**Comment by zhangjh** [comment]
看是否已经开源很简单啊，你为啥在这留言而不点进我的repo去看一下，我的都是开源的。ps：私有仓库要付费的，本人穷屌

**Comment by chantisnake** [comment]
哦，我今天早上在清理 issue，可能没仔细看，对不起

**Comment by xokctah** [comment]
首页已有链接。close this issue
