### ISSUE TITLE
偏远地区这样的医院比比皆是！！！

### ISSUE THREAD

**Issue by Changzw** [open-power-workgroup/Hospital#95]
不知道怎么说，像这样的医院太多了，很多偏远地区信息不发达，地区医疗水平不高，搜索百度永远是那几个知道花钱买广告的医院！！！
## 进去医院主页都是类似页面~~~贴几张“名医”的大头贴，闪动的聊天窗口，biubiu的提示音，最牛b的技术……

我能说我上大学期间我家人动手术被骗了二十多万吗？大城市和小城市之间的信息的不对等太明显了
希望大家，加大对偏远地区的莆田系医院的筛选（我知道几家肯定是！ 可是没有证据）

**Comment by langhua9527** [comment]
请整理提交

**Comment by xokctah** [comment]
@Changzw 可否请提交pull request?

**Comment by waitingHao** [comment]
@xokctah 

请问一下就诊记录是否能作为证据？

**Comment by xokctah** [comment]
要具体看就诊记录能反映哪些信息。我们的医院入选标准是：


   - 曾经投放百度竞价广告
   - 曾经被媒体报道过医疗欺诈事件
   - 与莆田系 <https://zh.wikipedia.org/wiki/%E8%8E%86%E7%94%B0%E7%B3%BB>存在直接关系

你掌握的就诊记录是否能直接或间接反映相关的信息？
