### ISSUE TITLE
贡献一下

### ISSUE THREAD

**Issue by kaixinsoft** [open-power-workgroup/Hospital#97]
http://mp.weixin.qq.com/s?__biz=MzA4MjQ1MTYwNQ==&mid=2652372650&idx=1&sn=3e29ab9d763a0bdc08d0878fa09deb2a&scene=2&srcid=0503Tls6J3rw0oHs4kfpUDzR&from=timeline&isappinstalled=0#wechat_redirect

**Comment by langhua9527** [comment]
整理提交一下啥

**Comment by imcaffrey** [comment]
该内容已被发布者删除

**Comment by xokctah** [comment]
网页已失效。
